// <auto-generated />
using System;
using ECommerce.TechnicalTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ECommerce.TechnicalTest.Data.Migrations
{
    [DbContext(typeof(ECommerceTechnicalTestDataContext))]
    [Migration("20250829080358_UpdateDataSeed")]
    partial class UpdateDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("PlacementDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ORDERS", "C##ECOMMERCE");
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.OrderItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ORDER_ITEM_DETAILS", "C##ECOMMERCE");
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("PRODUCTS", "C##ECOMMERCE");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3422),
                            Description = "Description for product 1",
                            Name = "Product _1 ",
                            Price = 7m,
                            StockQuantity = 101,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3519)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3635),
                            Description = "Description for product 2",
                            Name = "Product _2 ",
                            Price = 8m,
                            StockQuantity = 102,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3636)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3639),
                            Description = "Description for product 3",
                            Name = "Product _3 ",
                            Price = 9m,
                            StockQuantity = 103,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3640)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3688),
                            Description = "Description for product 4",
                            Name = "Product _4 ",
                            Price = 10m,
                            StockQuantity = 104,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3688)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3690),
                            Description = "Description for product 5",
                            Name = "Product _5 ",
                            Price = 11m,
                            StockQuantity = 105,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3690)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3698),
                            Description = "Description for product 6",
                            Name = "Product _6 ",
                            Price = 12m,
                            StockQuantity = 106,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3698)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3700),
                            Description = "Description for product 7",
                            Name = "Product _7 ",
                            Price = 13m,
                            StockQuantity = 107,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3700)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3701),
                            Description = "Description for product 8",
                            Name = "Product _8 ",
                            Price = 14m,
                            StockQuantity = 108,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3702)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3708),
                            Description = "Description for product 9",
                            Name = "Product _9 ",
                            Price = 15m,
                            StockQuantity = 109,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3708)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3712),
                            Description = "Description for product 10",
                            Name = "Product _10 ",
                            Price = 16m,
                            StockQuantity = 110,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3713)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3714),
                            Description = "Description for product 11",
                            Name = "Product _11 ",
                            Price = 17m,
                            StockQuantity = 111,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3715)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3716),
                            Description = "Description for product 12",
                            Name = "Product _12 ",
                            Price = 18m,
                            StockQuantity = 112,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3716)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3728),
                            Description = "Description for product 13",
                            Name = "Product _13 ",
                            Price = 19m,
                            StockQuantity = 113,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3728)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3732),
                            Description = "Description for product 14",
                            Name = "Product _14 ",
                            Price = 20m,
                            StockQuantity = 114,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3733)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3735),
                            Description = "Description for product 15",
                            Name = "Product _15 ",
                            Price = 21m,
                            StockQuantity = 115,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3735)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3737),
                            Description = "Description for product 16",
                            Name = "Product _16 ",
                            Price = 22m,
                            StockQuantity = 116,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3737)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3739),
                            Description = "Description for product 17",
                            Name = "Product _17 ",
                            Price = 23m,
                            StockQuantity = 117,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3739)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3742),
                            Description = "Description for product 18",
                            Name = "Product _18 ",
                            Price = 24m,
                            StockQuantity = 118,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3742)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3743),
                            Description = "Description for product 19",
                            Name = "Product _19 ",
                            Price = 25m,
                            StockQuantity = 119,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3743)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3745),
                            Description = "Description for product 20",
                            Name = "Product _20 ",
                            Price = 26m,
                            StockQuantity = 120,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3745)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3747),
                            Description = "Description for product 21",
                            Name = "Product _21 ",
                            Price = 27m,
                            StockQuantity = 121,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3747)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3748),
                            Description = "Description for product 22",
                            Name = "Product _22 ",
                            Price = 28m,
                            StockQuantity = 122,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3748)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3750),
                            Description = "Description for product 23",
                            Name = "Product _23 ",
                            Price = 29m,
                            StockQuantity = 123,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3750)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3752),
                            Description = "Description for product 24",
                            Name = "Product _24 ",
                            Price = 30m,
                            StockQuantity = 124,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3752)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3753),
                            Description = "Description for product 25",
                            Name = "Product _25 ",
                            Price = 31m,
                            StockQuantity = 125,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3754)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3755),
                            Description = "Description for product 26",
                            Name = "Product _26 ",
                            Price = 32m,
                            StockQuantity = 126,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3755)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3757),
                            Description = "Description for product 27",
                            Name = "Product _27 ",
                            Price = 33m,
                            StockQuantity = 127,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3757)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3758),
                            Description = "Description for product 28",
                            Name = "Product _28 ",
                            Price = 34m,
                            StockQuantity = 128,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3758)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3760),
                            Description = "Description for product 29",
                            Name = "Product _29 ",
                            Price = 35m,
                            StockQuantity = 129,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3760)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3762),
                            Description = "Description for product 30",
                            Name = "Product _30 ",
                            Price = 36m,
                            StockQuantity = 130,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 3, 57, 829, DateTimeKind.Utc).AddTicks(3762)
                        });
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.OrderItemDetail", b =>
                {
                    b.HasOne("ECommerce.TechnicalTest.Data.Entities.Order", "Order")
                        .WithMany("OrderedItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.TechnicalTest.Data.Entities.Product", "Product")
                        .WithMany("OrderItemDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderedItems");
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.Product", b =>
                {
                    b.Navigation("OrderItemDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
