// <auto-generated />
using System;
using ECommerce.TechnicalTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ECommerce.TechnicalTest.Data.Migrations
{
    [DbContext(typeof(ECommerceTechnicalTestDataContext))]
    [Migration("20250829080151_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("PlacementDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ORDERS", "C##ECOMMERCE");
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.OrderItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ORDER_ITEM_DETAILS", "C##ECOMMERCE");
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("PRODUCTS", "C##ECOMMERCE");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4383),
                            Description = "Description for product 1",
                            Name = "Product",
                            Price = 7m,
                            StockQuantity = 101,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4474)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4568),
                            Description = "Description for product 2",
                            Name = "Product",
                            Price = 8m,
                            StockQuantity = 102,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4568)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4571),
                            Description = "Description for product 3",
                            Name = "Product",
                            Price = 9m,
                            StockQuantity = 103,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4571)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4573),
                            Description = "Description for product 4",
                            Name = "Product",
                            Price = 10m,
                            StockQuantity = 104,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4573)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4575),
                            Description = "Description for product 5",
                            Name = "Product",
                            Price = 11m,
                            StockQuantity = 105,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4575)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4582),
                            Description = "Description for product 6",
                            Name = "Product",
                            Price = 12m,
                            StockQuantity = 106,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4582)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4626),
                            Description = "Description for product 7",
                            Name = "Product",
                            Price = 13m,
                            StockQuantity = 107,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4627)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4628),
                            Description = "Description for product 8",
                            Name = "Product",
                            Price = 14m,
                            StockQuantity = 108,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4628)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4630),
                            Description = "Description for product 9",
                            Name = "Product",
                            Price = 15m,
                            StockQuantity = 109,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4635)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4638),
                            Description = "Description for product 10",
                            Name = "Product",
                            Price = 16m,
                            StockQuantity = 110,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4639)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4640),
                            Description = "Description for product 11",
                            Name = "Product",
                            Price = 17m,
                            StockQuantity = 111,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4640)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4641),
                            Description = "Description for product 12",
                            Name = "Product",
                            Price = 18m,
                            StockQuantity = 112,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4641)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4643),
                            Description = "Description for product 13",
                            Name = "Product",
                            Price = 19m,
                            StockQuantity = 113,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4643)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4644),
                            Description = "Description for product 14",
                            Name = "Product",
                            Price = 20m,
                            StockQuantity = 114,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4644)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4645),
                            Description = "Description for product 15",
                            Name = "Product",
                            Price = 21m,
                            StockQuantity = 115,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4646)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4647),
                            Description = "Description for product 16",
                            Name = "Product",
                            Price = 22m,
                            StockQuantity = 116,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4647)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4648),
                            Description = "Description for product 17",
                            Name = "Product",
                            Price = 23m,
                            StockQuantity = 117,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4648)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4650),
                            Description = "Description for product 18",
                            Name = "Product",
                            Price = 24m,
                            StockQuantity = 118,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4650)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4660),
                            Description = "Description for product 19",
                            Name = "Product",
                            Price = 25m,
                            StockQuantity = 119,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4660)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4662),
                            Description = "Description for product 20",
                            Name = "Product",
                            Price = 26m,
                            StockQuantity = 120,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4662)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4663),
                            Description = "Description for product 21",
                            Name = "Product",
                            Price = 27m,
                            StockQuantity = 121,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4663)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4664),
                            Description = "Description for product 22",
                            Name = "Product",
                            Price = 28m,
                            StockQuantity = 122,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4665)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4666),
                            Description = "Description for product 23",
                            Name = "Product",
                            Price = 29m,
                            StockQuantity = 123,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4666)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4667),
                            Description = "Description for product 24",
                            Name = "Product",
                            Price = 30m,
                            StockQuantity = 124,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4667)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4671),
                            Description = "Description for product 25",
                            Name = "Product",
                            Price = 31m,
                            StockQuantity = 125,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4671)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4677),
                            Description = "Description for product 26",
                            Name = "Product",
                            Price = 32m,
                            StockQuantity = 126,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4677)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4679),
                            Description = "Description for product 27",
                            Name = "Product",
                            Price = 33m,
                            StockQuantity = 127,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4679)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4680),
                            Description = "Description for product 28",
                            Name = "Product",
                            Price = 34m,
                            StockQuantity = 128,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4680)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4681),
                            Description = "Description for product 29",
                            Name = "Product",
                            Price = 35m,
                            StockQuantity = 129,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4682)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4684),
                            Description = "Description for product 30",
                            Name = "Product",
                            Price = 36m,
                            StockQuantity = 130,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 1, 47, 41, DateTimeKind.Utc).AddTicks(4684)
                        });
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.OrderItemDetail", b =>
                {
                    b.HasOne("ECommerce.TechnicalTest.Data.Entities.Order", "Order")
                        .WithMany("OrderedItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.TechnicalTest.Data.Entities.Product", "Product")
                        .WithMany("OrderItemDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderedItems");
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.Product", b =>
                {
                    b.Navigation("OrderItemDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
