// <auto-generated />
using System;
using ECommerce.TechnicalTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ECommerce.TechnicalTest.Data.Migrations
{
    [DbContext(typeof(ECommerceTechnicalTestDataContext))]
    [Migration("20250829080639_UpdateDataSeeding1")]
    partial class UpdateDataSeeding1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("PlacementDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ORDERS", "C##ECOMMERCE");
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.OrderItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ORDER_ITEM_DETAILS", "C##ECOMMERCE");
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("PRODUCTS", "C##ECOMMERCE");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(259),
                            Description = "Description for product 1",
                            Name = "Product_1 ",
                            Price = 7m,
                            StockQuantity = 101,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(364)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(473),
                            Description = "Description for product 2",
                            Name = "Product_2 ",
                            Price = 8m,
                            StockQuantity = 102,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(473)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(477),
                            Description = "Description for product 3",
                            Name = "Product_3 ",
                            Price = 9m,
                            StockQuantity = 103,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(477)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(480),
                            Description = "Description for product 4",
                            Name = "Product_4 ",
                            Price = 10m,
                            StockQuantity = 104,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(480)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(482),
                            Description = "Description for product 5",
                            Name = "Product_5 ",
                            Price = 11m,
                            StockQuantity = 105,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(482)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(489),
                            Description = "Description for product 6",
                            Name = "Product_6 ",
                            Price = 12m,
                            StockQuantity = 106,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(490)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(491),
                            Description = "Description for product 7",
                            Name = "Product_7 ",
                            Price = 13m,
                            StockQuantity = 107,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(491)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(493),
                            Description = "Description for product 8",
                            Name = "Product_8 ",
                            Price = 14m,
                            StockQuantity = 108,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(493)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(500),
                            Description = "Description for product 9",
                            Name = "Product_9 ",
                            Price = 15m,
                            StockQuantity = 109,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(501)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(505),
                            Description = "Description for product 10",
                            Name = "Product_10 ",
                            Price = 16m,
                            StockQuantity = 110,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(505)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(507),
                            Description = "Description for product 11",
                            Name = "Product_11 ",
                            Price = 17m,
                            StockQuantity = 111,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(507)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(509),
                            Description = "Description for product 12",
                            Name = "Product_12 ",
                            Price = 18m,
                            StockQuantity = 112,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(509)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(519),
                            Description = "Description for product 13",
                            Name = "Product_13 ",
                            Price = 19m,
                            StockQuantity = 113,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(519)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(581),
                            Description = "Description for product 14",
                            Name = "Product_14 ",
                            Price = 20m,
                            StockQuantity = 114,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(581)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(584),
                            Description = "Description for product 15",
                            Name = "Product_15 ",
                            Price = 21m,
                            StockQuantity = 115,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(584)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(586),
                            Description = "Description for product 16",
                            Name = "Product_16 ",
                            Price = 22m,
                            StockQuantity = 116,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(586)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(588),
                            Description = "Description for product 17",
                            Name = "Product_17 ",
                            Price = 23m,
                            StockQuantity = 117,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(588)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(590),
                            Description = "Description for product 18",
                            Name = "Product_18 ",
                            Price = 24m,
                            StockQuantity = 118,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(591)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(592),
                            Description = "Description for product 19",
                            Name = "Product_19 ",
                            Price = 25m,
                            StockQuantity = 119,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(592)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(594),
                            Description = "Description for product 20",
                            Name = "Product_20 ",
                            Price = 26m,
                            StockQuantity = 120,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(594)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(596),
                            Description = "Description for product 21",
                            Name = "Product_21 ",
                            Price = 27m,
                            StockQuantity = 121,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(596)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(597),
                            Description = "Description for product 22",
                            Name = "Product_22 ",
                            Price = 28m,
                            StockQuantity = 122,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(597)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(599),
                            Description = "Description for product 23",
                            Name = "Product_23 ",
                            Price = 29m,
                            StockQuantity = 123,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(599)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(601),
                            Description = "Description for product 24",
                            Name = "Product_24 ",
                            Price = 30m,
                            StockQuantity = 124,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(601)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(602),
                            Description = "Description for product 25",
                            Name = "Product_25 ",
                            Price = 31m,
                            StockQuantity = 125,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(603)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(604),
                            Description = "Description for product 26",
                            Name = "Product_26 ",
                            Price = 32m,
                            StockQuantity = 126,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(604)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(606),
                            Description = "Description for product 27",
                            Name = "Product_27 ",
                            Price = 33m,
                            StockQuantity = 127,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(606)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(607),
                            Description = "Description for product 28",
                            Name = "Product_28 ",
                            Price = 34m,
                            StockQuantity = 128,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(608)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(609),
                            Description = "Description for product 29",
                            Name = "Product_29 ",
                            Price = 35m,
                            StockQuantity = 129,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(609)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(611),
                            Description = "Description for product 30",
                            Name = "Product_30 ",
                            Price = 36m,
                            StockQuantity = 130,
                            UpdatedAt = new DateTime(2025, 8, 29, 8, 6, 39, 307, DateTimeKind.Utc).AddTicks(611)
                        });
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.OrderItemDetail", b =>
                {
                    b.HasOne("ECommerce.TechnicalTest.Data.Entities.Order", "Order")
                        .WithMany("OrderedItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.TechnicalTest.Data.Entities.Product", "Product")
                        .WithMany("OrderItemDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderedItems");
                });

            modelBuilder.Entity("ECommerce.TechnicalTest.Data.Entities.Product", b =>
                {
                    b.Navigation("OrderItemDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
